title: <p align="center"> Ravinder Singh </p>
logo: /assets/img/IMG_7485.JPG

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/ravinder-singh-68bb801a3/">LinkedIn</a> |
  <a href="https://github.com/ravindersingh33/">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
